"""Compatibility wrapper for the split Task 2 allocation algorithms."""

from app.algorithms import (
    AVLNode,
    Incident,
    Options,
    PRIORITY,
    Problem,
    Requirement,
    ResponseCache,
    STRATEGIES,
    Vehicle,
    Weights,
    allocate,
    avl_insert,
    avl_order,
    canonical,
    genetic,
    greedy,
    height,
    min_cost_flow,
    rotate,
    vehicle_kind,
)

__all__ = [
    "PRIORITY",
    "STRATEGIES",
    "Requirement",
    "Weights",
    "Options",
    "Incident",
    "Vehicle",
    "ResponseCache",
    "AVLNode",
    "height",
    "rotate",
    "avl_insert",
    "avl_order",
    "canonical",
    "vehicle_kind",
    "Problem",
    "greedy",
    "min_cost_flow",
    "genetic",
    "allocate",
]
