[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*Using .httpx. with .starlette.testclient. is deprecated.*
    ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*
    ignore:.*The .timeout. parameter is deprecated.*
    ignore:.*The .verify. parameter is deprecated.*
